---
# $Author$
# $Date$
# $Source$

# agent-install tasks file for opsview-agent
#- name: Check the version of the Opsview-Agent installed
#  block:
- name: Update OpsView Agent version
  debug:
    msg:  "Upgrading OpsView Agent version {{ opsview_agent_current_version }} to {{ opsview_agent_version }}"

- name: Calculate the OpsView Agent source and target
  set_fact:
    opsview_source_file:      "files/opsview/agents/{{ opsview_agent_package }}"
    opsview_destination_file: "/tmp/{{ opsview_agent_package }}"

- name: Copy OpsView Agent rpm file to server
  copy:
    src:   "files/opsview/agents/{{ opsview_agent_package }}"
    dest:  "/tmp/{{ opsview_agent_package }}"
    owner: root
    group: root
    mode:  '0600'

- name: Install the OpsView Agent package.
  package:
    name:         "/tmp/{{ opsview_agent_package }}"
    state:        present
  ignore_errors:  "{{ ansible_check_mode }}"
  notify:         Restart OpsView
