---
# $Author$
# $Date$
# $Source$

# tasks file for opsview-agent
- name: Get the version of Opsview-Agent installed
  package:
    list:    opsview-agent
  register:  opsview_agent_current_version

- name: Set opsview_agent_current_version with the current version installed
  set_fact:
    opsview_agent_current_version:  "{{ opsview_agent_current_version.results[0].version }}"

- name: Install the OpsView agent if needed
  include_tasks: agent_install.yml
  when:          (opsview_agent_version is version(opsview_agent_current_version, '>'))

- name: Configure local extensions for the OpsView Agent
  include_tasks: agent_local_config.yml

- name: OpsView Agent version is current
  debug:
    msg:  "OpsView Agent version {{ opsview_agent_current_version }} is already current"
  when:   (opsview_agent_version is version(opsview_agent_current_version, '<='))
