---
# $Author$
# $Date$
# $Source$

# plugin-install file for opsview-agent
#- name: Installing plug-in {{ plugin_item.name }}
#  debug:
#    msg: "Installing plug-in {{ plugin_item.name }}"

#- name: Copy the source to the local plug-in directory
#  copy:
#    src:   "{{ opsview_agent_plugin_source }}/{{ plugin_item.name }}"
#    dest:  "{{ opsview_agent_plugin_local }}/{{ plugin_item.name }}"
#    owner: root
#    group: root
#    mode:  '0600'

- name: Create the {{ plugin_item.name }} configuration file
  template:
    src:    plugin_cfg.j2
    dest:   "{{ opsview_agent_cfg_local }}/{{ plugin_item.name }}.cfg"
    owner:  "{{ opsview_agent_user }}"
    group:  "{{ opsview_agent_group }}"
    mode:   '0644'
    backup: false
  notify:   Restart OpsView Agent

- name: Create list of sources to install
  set_fact:
    opsview_agent_plugin_source_list: "{{ ((plugin_item.source | default([])) | list + [ plugin_item.name ]) | unique }}"

- name: Copy the source for {{ plugin_item.name }} to the plug-in directory
  copy:
    src:    "{{ opsview_agent_plugin_source }}/{{ item }}"
    dest:   "{{ opsview_agent_plugin_local }}/{{ item }}"
    owner:  "{{ opsview_agent_user }}"
    group:  "{{ opsview_agent_group }}"
    mode:   '0644'
  loop:     "{{ opsview_agent_plugin_source_list }}"

#- name: Create the plug-in configuration file
#  template:
#    src:    plugin_cfg.j2
#    dest:   "{{ opsview_agent_cfg_local }}/{{ plugin_item.name }}.cfg"
#    owner:  "{{ opsview_agent_user }}"
#    group:  "{{ opsview_agent_group }}"
#    mode:   '0644'
#    backup: false

- name: Create the sudoers entry if requested
  include_tasks:  plugin_sudo.yml
  when:           plugin_item.sudo is defined
