---
# $Author$
# $Date$
# $Source$

# plugin-install file for opsview-agent

#- name: Dump the host variables oin the plugin_install tasks
#  debug:
#    var:  vars

- name: Display the name of the plugin
  debug:
    msg: "Processing plug-in named {{ plugin_item.name }}"

- name: Display the sudo status of the plugin
  debug:
    msg: "Plug-in requires sudo {{ plugin_item.sudo }}"

- name: Installing plug-in {{ plugin_item.name }}
  debug:
    msg: "Installing plug-in {{ plugin_item.name }}"

- name: Copy the source to the local plug-in directory
  copy:
    src:   "{{ opsview_agent_plugin_source }}/{{ plugin_item.name }}"
    dest:  "{{ opsview_agent_plugin_local }}/{{ plugin_item.name }}"
    owner: root
    group: root
    mode:  '0600'

- name: Create list of sources to install
  set_fact:
    opsview_agent_plugin_source_list: "{{ ((plugin_item.source | default([])) | list + [ plugin_item.name ]) | unique }}"

- name: Dump created source list
  debug:
    var: opsview_agent_plugin_source_list

- name: Copy the source to the local plug-in directory
  copy:
    src:   "{{ opsview_agent_plugin_source }}/{{ item }}"
    dest:  "{{ opsview_agent_plugin_local }}/{{ item }}"
    owner: root
    group: root
    mode:  '0600'
  loop:    opsview_agent_plugin_source_list
#  when:    plugin_item.source is defined
#  loop:    "{{ plugin_item.source | default([]) }}"
#  loop:    "plugin_item.source | default([]) | list + [ plugin_item.name ] | unique"
