---
# $Author$
# $Date$
# $Source$

# plugin-install file for opsview-agent

#- name: Dump the host variables oin the plugin_install tasks
#  debug:
#    var:  vars

- name: Display the name of the plugin
  debug:
    msg: "Processing plug-in named {{ plugin_item.name }}"

- name: Display the sources of the plugin
  debug:
    msg: "Plug-in sources {{ plugin_item.source }}"
  when: plugin_item.source is defined

- name: Display the sudo status of the plugin
  debug:
    msg: "Plug-in requires sudo {{ plugin_item.sudo }}"

- name: Display the name of the plugin
  debug:
    msg: "Processing plug-in named {{ plugin_item.name }}"

- name: Installing plug-in {{ plugin_item.name }}
  debug:
    msg: "Installing plug-in {{ plugin_item.name }}"

- name: Copy the source to the local plug-in directory
  copy:
    src:   "{{ opsview_agent_plugin_source }}/{{ plugin_item.name }}"
    dest:  "{{ opsview_agent_plugin_local }}/{{ plugin_item.name }}"
    owner: root
    group: root
    mode:  '0600'

- name: Dump plugin sources
  debug:
    var: plugin_item.source
  when:  plugin_item.source is defined

- name: Dump plugin name
  debug:
    var: plugin_item.name

- name: Dump plugin sources to install
  debug:
    var: ({{ plugin_item.source | default([]) }} | list) + [ {{ plugin.name }} ]

- name: Dump unique plugin sources to install
  debug:
    var: "plugin_item.source | default([]) | list + [ plugin.name ]"

- name: Copy the source to the local plug-in directory
  copy:
    src:   "{{ opsview_agent_plugin_source }}/{{ item }}"
    dest:  "{{ opsview_agent_plugin_local }}/{{ item }}"
    owner: root
    group: root
    mode:  '0600'
  loop:    "plugin_item.source | default([]) | list + [ plugin_item.name ] | unique"
#  when:    plugin_item.source is defined
#  loop:    "{{ plugin_item.source | default([]) }}"
